[workspace]

members = [
  "completion-core",
  "completion-derive",
  "completion-plugin",
  "completion-sources/*",
]

exclude = [ "completion-sources/runtime" ]

[profile.release]
lto = true
codegen-units = 1
