[package]
name = "compleet-lipsum"
version = "0.1.0"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"

[dependencies]
async-trait = "0.1"
compleet-core = { path = "../../compleet-core" }
