pub const LOREM_IPSUM: &[&str] = &[
    "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus elit,",
    "vestibulum ut, placerat ac, adipiscing vitae, felis. Curabitur dictum \
     gravida",
    "mauris. Nam arcu libero, nonummy eget, consectetuer id, vulputate a, \
     magna.",
    "Donec vehicula augue eu neque. Pellentesque habitant morbi tristique \
     senectus",
    "et netus et malesuada fames ac turpis egestas. Mauris ut leo. Cras \
     viverra",
    "metus rhoncus sem. Nulla et lectus vestibulum urna fringilla ultrices.",
    "Phasellus eu tellus sit amet tortor gravida placerat. Integer sapien est",
    "iaculis in, pretium quis, viverra ac, nunc. Praesent eget sem vel leo \
     ultrices",
    "bibendum. Aenean faucibus. Morbi dolor nulla, malesuada eu, pulvinar \
     at, mollis",
    "ac, nulla. Curabitur auctor semper nulla. Donec varius orci eget risus. \
     Duis",
    "nibh mi, congue eu, accumsan eleifend, sagittis quis, diam. Duis eget \
     orci sit",
    "amet orci dignissim",
];

pub const LOREMS: &[&str] = &[
    "Lorem",
    "ipsum",
    "dolor",
    "sit",
    "amet",
    "consectetuer",
    "adipiscing",
    "elit",
    "Ut",
    "purus",
    "elit",
    "vestibulum",
    "ut",
    "placerat",
    "ac",
    "adipiscing",
    "vitae",
    "felis",
    "Curabitur",
    "dictum",
    "gravida",
    "mauris",
    "Nam",
    "arcu",
    "libero",
    "nonummy",
    "eget",
    "consectetuer",
    "id",
    "vulputate",
    "a",
    "magna",
    "Donec",
    "vehicula",
    "augue",
    "eu",
    "neque",
    "Pellentesque",
    "habitant",
    "morbi",
    "tristique",
    "senectus",
    "et",
    "netus",
    "et",
    "malesuada",
    "fames",
    "ac",
    "turpis",
    "egestas",
    "Mauris",
    "ut",
    "leo",
    "Cras",
    "viverra",
    "metus",
    "rhoncus",
    "sem",
    "Nulla",
    "et",
    "lectus",
    "vestibulum",
    "urna",
    "fringilla",
    "ultrices",
    "Phasellus",
    "eu",
    "tellus",
    "sit",
    "amet",
    "tortor",
    "gravida",
    "placerat",
    "Integer",
    "sapien",
    "est",
    "iaculis",
    "in",
    "pretium",
    "quis",
    "viverra",
    "ac",
    "nunc",
    "Praesent",
    "eget",
    "sem",
    "vel",
    "leo",
    "ultrices",
    "bibendum",
    "Aenean",
    "faucibus",
    "Morbi",
    "dolor",
    "nulla",
    "malesuada",
    "eu",
    "pulvinar",
    "at",
    "mollis",
    "ac",
    "nulla",
    "Curabitur",
    "auctor",
    "semper",
    "nulla",
    "Donec",
    "varius",
    "orci",
    "eget",
    "risus",
    "Duis",
    "nibh",
    "mi",
    "congue",
    "eu",
    "accumsan",
    "eleifend",
    "sagittis",
    "quis",
    "diam",
    "Duis",
    "eget",
    "orci",
    "sit",
    "amet",
    "orci",
    "dignissim",
];
