mod autocmds;
mod client;
mod commands;
mod completion_item_ext;
mod config;
mod document_ext;
mod error;
mod hlgroups;
mod lateinit;
mod mappings;
mod messages;
mod position_ext;
mod setup;
mod source_bundle_ext;
mod ui;
mod utils;

use client::Client;
use completion_item_ext::CompletionItemExt;
use document_ext::DocumentExt;
use error::{Error, Result};
use position_ext::PositionExt;
pub use setup::{build_api, register_source};
use source_bundle_ext::SourceBundleExt;
